javascripts:
  app:
    - public/javascripts/jquery.min.js
    - public/javascripts/application.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/json2.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone-0.5.0.js
    - public/javascripts/icanhaz.js
    - public/javascripts/songs.js
    - app/views/songs/*.jst    